kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: appache1
rules:
  - apiGroups: ["", "apps", "rbac.authorization.k8s.io", "batch"]
    resources: ["deployments", "pods", "services"]
    verbs: ["get", "apply", "delete", "watch", "create", "patch"]
