kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appache-manager-rolebinding
  namespace: appache1
subjects:
  - kind: User
    name: appache-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: apache-manager
  apiGroup: rbac.authorization.k8s.io
