apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: appache-vpa
  namespace: appache1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appache-dep
  updatePolicy:
    updateMode: "Auto"
